<?php
/**
 * ACF Field Group Registrations.
 *
 * All field groups for the theme.
 * Auto-generated on 2026-02-12 21:10:18
 *
 * @package EBCA_Theme
 * @since 1.0.0
 */

if ( ! function_exists( 'acf_add_local_field_group' ) ) {
	return;
}

/**
 * Field Group: Collection fields
 */
acf_add_local_field_group( array(
	'key' => 'group_64c25d318a6f1',
	'title' => 'Collection fields',
	'fields' => array(
		0 => array(
			'ID' => 0,
			'key' => 'field_64f393ee80b98',
			'label' => 'Flexible Content',
			'name' => 'flexible_content',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'flexible_content',
			'value' => NULL,
			'menu_order' => 0,
			'instructions' => '',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_64c25d318a6f1',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_64f393f1940ee' => array(
					'key' => 'layout_64f393f1940ee',
					'name' => 'gallery',
					'label' => 'Gallery',
					'display' => 'block',
					'sub_fields' => array(
						0 => array(
							'ID' => 0,
							'key' => 'field_67ac1234567a0',
							'label' => 'Disable shadows for all images',
							'name' => 'disable_shadows_all',
							'aria-label' => '',
							'prefix' => 'acf',
							'type' => 'true_false',
							'value' => NULL,
							'menu_order' => 0,
							'instructions' => 'Check to remove shadows from all images in this gallery. Individual images can still override this setting.',
							'required' => 0,
							'id' => '',
							'class' => '',
							'conditional_logic' => 0,
							'parent' => 'field_64f393ee80b98',
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => 'Yes',
							'ui_off_text' => 'No',
							'parent_layout' => 'layout_64f393f1940ee',
							'_name' => 'disable_shadows_all',
							'_valid' => 1,
						),
						1 => array(
							'ID' => 0,
							'key' => 'field_64f3949a80b9c',
							'label' => 'Images',
							'name' => 'images',
							'aria-label' => '',
							'prefix' => 'acf',
							'type' => 'repeater',
							'value' => NULL,
							'menu_order' => 1,
							'instructions' => '',
							'required' => 0,
							'id' => '',
							'class' => '',
							'conditional_logic' => 0,
							'parent' => 'field_64f393ee80b98',
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Image',
							'rows_per_page' => 20,
							'parent_layout' => 'layout_64f393f1940ee',
							'_name' => 'images',
							'_valid' => 1,
							'sub_fields' => array(
								0 => array(
									'ID' => 0,
									'key' => 'field_64f394a480b9d',
									'label' => 'Image',
									'name' => 'attachment_id',
									'aria-label' => '',
									'prefix' => 'acf',
									'type' => 'image',
									'value' => NULL,
									'menu_order' => 0,
									'instructions' => 'Select an image.',
									'required' => 1,
									'id' => '',
									'class' => '',
									'conditional_logic' => 0,
									'parent' => 'field_64f3949a80b9c',
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'id',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
									'preview_size' => 'medium',
									'parent_repeater' => 'field_64f3949a80b9c',
									'_name' => 'attachment_id',
									'_valid' => 1,
								),
								1 => array(
									'ID' => 0,
									'key' => 'field_64f3a36261888',
									'label' => 'Added at',
									'name' => 'added_at',
									'aria-label' => '',
									'prefix' => 'acf',
									'type' => 'date_picker',
									'value' => NULL,
									'menu_order' => 1,
									'instructions' => 'Select date image added to this Collection.',
									'required' => 1,
									'id' => '',
									'class' => '',
									'conditional_logic' => 0,
									'parent' => 'field_64f3949a80b9c',
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'display_format' => 'Y-m-d',
									'return_format' => 'Y-m-d',
									'first_day' => 0,
									'default_to_current_date' => 0,
									'default_value' => '20260212',
									'parent_repeater' => 'field_64f3949a80b9c',
									'_name' => 'added_at',
									'_valid' => 1,
								),
								2 => array(
									'ID' => 0,
									'key' => 'field_67ac1234567a1',
									'label' => 'Disable shadow',
									'name' => 'disable_shadow',
									'aria-label' => '',
									'prefix' => 'acf',
									'type' => 'true_false',
									'value' => NULL,
									'menu_order' => 2,
									'instructions' => 'Check to remove shadow from this image.',
									'required' => 0,
									'id' => '',
									'class' => '',
									'conditional_logic' => 0,
									'parent' => 'field_64f3949a80b9c',
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 1,
									'ui_on_text' => 'Yes',
									'ui_off_text' => 'No',
									'parent_repeater' => 'field_64f3949a80b9c',
									'_name' => 'disable_shadow',
									'_valid' => 1,
								),
							),
						),
					),
					'min' => '1',
					'max' => '',
				),
				'layout_64f394f3cd28f' => array(
					'key' => 'layout_64f394f3cd28f',
					'name' => 'text',
					'label' => 'Text',
					'display' => 'block',
					'sub_fields' => array(
						0 => array(
							'ID' => 0,
							'key' => 'field_64f394fecd291',
							'label' => 'Content',
							'name' => 'content',
							'aria-label' => '',
							'prefix' => 'acf',
							'type' => 'wysiwyg',
							'value' => NULL,
							'menu_order' => 0,
							'instructions' => '',
							'required' => 0,
							'id' => '',
							'class' => '',
							'conditional_logic' => 0,
							'parent' => 'field_64f393ee80b98',
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 0,
							'delay' => 0,
							'parent_layout' => 'layout_64f394f3cd28f',
							'_name' => 'content',
							'_valid' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Add Row',
			'_name' => 'flexible_content',
			'_valid' => 1,
		),
	),
	'location' => array(
		0 => array(
			0 => array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'collection',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'_valid' => true,
	'local_file' => '/Users/eric/Sites/ericbusch-ca/wp-content/themes/ebca-theme/acf-json/group_64c25d318a6f1.json',
) );

/**
 * Field Group: Homepage Fields
 */
acf_add_local_field_group( array(
	'key' => 'group_64c1ba294429b',
	'title' => 'Homepage Fields',
	'fields' => array(
		0 => array(
			'ID' => 0,
			'key' => 'field_64c1ba294bd20',
			'label' => 'Background Images',
			'name' => 'background_images',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'repeater',
			'value' => NULL,
			'menu_order' => 0,
			'instructions' => '',
			'required' => 1,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_64c1ba294429b',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 1,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Image',
			'rows_per_page' => 20,
			'_name' => 'background_images',
			'_valid' => 1,
			'sub_fields' => array(
				0 => array(
					'ID' => 0,
					'key' => 'field_64c1ba484bd21',
					'label' => 'Image',
					'name' => 'image',
					'aria-label' => '',
					'prefix' => 'acf',
					'type' => 'image',
					'value' => NULL,
					'menu_order' => 0,
					'instructions' => '',
					'required' => 1,
					'id' => '',
					'class' => '',
					'conditional_logic' => 0,
					'parent' => 'field_64c1ba294bd20',
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'parent_repeater' => 'field_64c1ba294bd20',
					'_name' => 'image',
					'_valid' => 1,
				),
			),
		),
		1 => array(
			'ID' => 0,
			'key' => 'field_64c1c6225f20b',
			'label' => 'Heading One',
			'name' => 'heading_one',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'text',
			'value' => NULL,
			'menu_order' => 1,
			'instructions' => '',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_64c1ba294429b',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'_name' => 'heading_one',
			'_valid' => 1,
		),
		2 => array(
			'ID' => 0,
			'key' => 'field_64c1c632904c1',
			'label' => 'Heading Two',
			'name' => 'heading_two',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'text',
			'value' => NULL,
			'menu_order' => 2,
			'instructions' => '',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_64c1ba294429b',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'_name' => 'heading_two',
			'_valid' => 1,
		),
		3 => array(
			'ID' => 0,
			'key' => 'field_64c1c639ab17c',
			'label' => 'Button Text',
			'name' => 'button_text',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'text',
			'value' => NULL,
			'menu_order' => 3,
			'instructions' => '',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_64c1ba294429b',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'_name' => 'button_text',
			'_valid' => 1,
		),
		4 => array(
			'ID' => 0,
			'key' => 'field_64c1c9ed20a3d',
			'label' => 'Button URL',
			'name' => 'button_url',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'page_link',
			'value' => NULL,
			'menu_order' => 4,
			'instructions' => '',
			'required' => 1,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_64c1ba294429b',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => '',
			'post_status' => '',
			'taxonomy' => '',
			'allow_archives' => 1,
			'multiple' => 0,
			'allow_null' => 0,
			'_name' => 'button_url',
			'_valid' => 1,
		),
		5 => array(
			'ID' => 0,
			'key' => 'field_64c25a2fe5d19',
			'label' => 'Fine Print',
			'name' => 'fine_print',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'text',
			'value' => NULL,
			'menu_order' => 5,
			'instructions' => '',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_64c1ba294429b',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'_name' => 'fine_print',
			'_valid' => 1,
		),
	),
	'location' => array(
		0 => array(
			0 => array(
				'param' => 'page',
				'operator' => '==',
				'value' => '15',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'_valid' => true,
	'local_file' => '/Users/eric/Sites/ericbusch-ca/wp-content/themes/ebca-theme/acf-json/group_64c1ba294429b.json',
) );

/**
 * Field Group: Issue fields
 */
acf_add_local_field_group( array(
	'key' => 'group_695d5d7127bc3',
	'title' => 'Issue fields',
	'fields' => array(
		0 => array(
			'ID' => 0,
			'key' => 'field_695d5d71b7974',
			'label' => 'Number',
			'name' => 'issue_number',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'number',
			'value' => NULL,
			'menu_order' => 0,
			'instructions' => 'What issue number is this?',
			'required' => 1,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_695d5d7127bc3',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => 0,
			'max' => 1000,
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
			'_name' => 'issue_number',
			'_valid' => 1,
		),
		1 => array(
			'ID' => 0,
			'key' => 'field_696167a274e72',
			'label' => 'Guest',
			'name' => 'guest',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'text',
			'value' => NULL,
			'menu_order' => 1,
			'instructions' => '',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_695d5d7127bc3',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => 'Ansel Adams',
			'prepend' => '',
			'append' => '',
			'_name' => 'guest',
			'_valid' => 1,
		),
		2 => array(
			'ID' => 0,
			'key' => 'field_69665b253a020',
			'label' => 'Kit Link',
			'name' => 'kit_link',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'url',
			'value' => NULL,
			'menu_order' => 2,
			'instructions' => 'Link to post on Kit.com',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_695d5d7127bc3',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'_name' => 'kit_link',
			'_valid' => 1,
		),
		3 => array(
			'ID' => 0,
			'key' => 'field_695eba4273987',
			'label' => 'Images',
			'name' => 'images',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'repeater',
			'value' => NULL,
			'menu_order' => 3,
			'instructions' => '',
			'required' => 1,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_695d5d7127bc3',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 2,
			'max' => 2,
			'collapsed' => '',
			'button_label' => 'Add Image',
			'rows_per_page' => 20,
			'_name' => 'images',
			'_valid' => 1,
			'sub_fields' => array(
				0 => array(
					'ID' => 0,
					'key' => 'field_695eba4d73988',
					'label' => 'Photographer',
					'name' => 'photographer',
					'aria-label' => '',
					'prefix' => 'acf',
					'type' => 'post_object',
					'value' => NULL,
					'menu_order' => 0,
					'instructions' => '',
					'required' => 0,
					'id' => '',
					'class' => '',
					'conditional_logic' => 0,
					'parent' => 'field_695eba4273987',
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array(
						0 => 'photographer',
					),
					'post_status' => '',
					'taxonomy' => '',
					'return_format' => 'object',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'bidirectional' => 0,
					'ui' => 1,
					'bidirectional_target' => array(
					),
					'parent_repeater' => 'field_695eba4273987',
					'_name' => 'photographer',
					'_valid' => 1,
				),
				1 => array(
					'ID' => 0,
					'key' => 'field_695eba8073989',
					'label' => 'Image',
					'name' => 'image',
					'aria-label' => '',
					'prefix' => 'acf',
					'type' => 'image',
					'value' => NULL,
					'menu_order' => 1,
					'instructions' => '',
					'required' => 1,
					'id' => '',
					'class' => '',
					'conditional_logic' => 0,
					'parent' => 'field_695eba4273987',
					'wrapper' => array(
						'width' => '49',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 0,
					'preview_size' => 'medium',
					'parent_repeater' => 'field_695eba4273987',
					'_name' => 'image',
					'_valid' => 1,
				),
				2 => array(
					'ID' => 0,
					'key' => 'field_695ebaab7398a',
					'label' => 'Title',
					'name' => 'title',
					'aria-label' => '',
					'prefix' => 'acf',
					'type' => 'text',
					'value' => NULL,
					'menu_order' => 2,
					'instructions' => '',
					'required' => 0,
					'id' => '',
					'class' => '',
					'conditional_logic' => 0,
					'parent' => 'field_695eba4273987',
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_695eba4273987',
					'_name' => 'title',
					'_valid' => 1,
				),
				3 => array(
					'ID' => 0,
					'key' => 'field_695ebac07398b',
					'label' => 'Thoughts',
					'name' => 'thoughts',
					'aria-label' => '',
					'prefix' => 'acf',
					'type' => 'wysiwyg',
					'value' => NULL,
					'menu_order' => 3,
					'instructions' => '',
					'required' => 0,
					'id' => '',
					'class' => '',
					'conditional_logic' => 0,
					'parent' => 'field_695eba4273987',
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'tabs' => 'visual',
					'toolbar' => 'basic',
					'media_upload' => 0,
					'delay' => 0,
					'parent_repeater' => 'field_695eba4273987',
					'_name' => 'thoughts',
					'_valid' => 1,
				),
			),
		),
	),
	'location' => array(
		0 => array(
			0 => array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'issue',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'_valid' => true,
	'local_file' => '/Users/eric/Sites/ericbusch-ca/wp-content/themes/ebca-theme/acf-json/group_695d5d7127bc3.json',
) );

/**
 * Field Group: Photographer fields
 */
acf_add_local_field_group( array(
	'key' => 'group_695e6e9153181',
	'title' => 'Photographer fields',
	'fields' => array(
		0 => array(
			'ID' => 0,
			'key' => 'field_695e6e91e83b8',
			'label' => 'Name',
			'name' => 'name',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'text',
			'value' => NULL,
			'menu_order' => 0,
			'instructions' => '',
			'required' => 1,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_695e6e9153181',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'_name' => 'name',
			'_valid' => 1,
		),
		1 => array(
			'ID' => 0,
			'key' => 'field_69616402220bf',
			'label' => 'Is me',
			'name' => 'is_me',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'true_false',
			'value' => NULL,
			'menu_order' => 1,
			'instructions' => 'Is this photographer you (Eric) or not?',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_695e6e9153181',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'_name' => 'is_me',
			'_valid' => 1,
		),
		2 => array(
			'ID' => 0,
			'key' => 'field_695e6ea1e83ba',
			'label' => 'Bio',
			'name' => 'bio',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'wysiwyg',
			'value' => NULL,
			'menu_order' => 2,
			'instructions' => '',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_695e6e9153181',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
			'_name' => 'bio',
			'_valid' => 1,
		),
		3 => array(
			'ID' => 0,
			'key' => 'field_695e6ec9e83bb',
			'label' => 'Links',
			'name' => 'links',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'repeater',
			'value' => NULL,
			'menu_order' => 3,
			'instructions' => '',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_695e6e9153181',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Link',
			'rows_per_page' => 20,
			'_name' => 'links',
			'_valid' => 1,
			'sub_fields' => array(
				0 => array(
					'ID' => 0,
					'key' => 'field_695e6ed9e83bc',
					'label' => 'Channel',
					'name' => 'channel',
					'aria-label' => '',
					'prefix' => 'acf',
					'type' => 'select',
					'value' => NULL,
					'menu_order' => 0,
					'instructions' => '',
					'required' => 0,
					'id' => '',
					'class' => '',
					'conditional_logic' => 0,
					'parent' => 'field_695e6ec9e83bb',
					'wrapper' => array(
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'website' => 'Website',
						'instagram' => 'Instagram',
						'facebook' => 'Facebook',
						'flickr' => 'Flickr',
						'bluesky' => 'Blue Sky',
						'vero' => 'Vero',
						'fivehundredpx' => '500px',
						'glass' => 'Glass',
						'representation' => 'Gallery Representation',
					),
					'default_value' => false,
					'return_format' => 'array',
					'multiple' => 0,
					'allow_null' => 0,
					'allow_in_bindings' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'create_options' => 0,
					'save_options' => 0,
					'parent_repeater' => 'field_695e6ec9e83bb',
					'_name' => 'channel',
					'_valid' => 1,
				),
				1 => array(
					'ID' => 0,
					'key' => 'field_695e6f7be83bd',
					'label' => 'URL',
					'name' => 'url',
					'aria-label' => '',
					'prefix' => 'acf',
					'type' => 'url',
					'value' => NULL,
					'menu_order' => 1,
					'instructions' => '',
					'required' => 1,
					'id' => '',
					'class' => '',
					'conditional_logic' => 0,
					'parent' => 'field_695e6ec9e83bb',
					'wrapper' => array(
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_695e6ec9e83bb',
					'_name' => 'url',
					'_valid' => 1,
				),
			),
		),
	),
	'location' => array(
		0 => array(
			0 => array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'photographer',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'_valid' => true,
	'local_file' => '/Users/eric/Sites/ericbusch-ca/wp-content/themes/ebca-theme/acf-json/group_695e6e9153181.json',
) );

/**
 * Field Group: Site Options
 */
acf_add_local_field_group( array(
	'key' => 'group_64c1b21c4c024',
	'title' => 'Site Options',
	'fields' => array(
		0 => array(
			'ID' => 0,
			'key' => 'field_64c1b21c81fea',
			'label' => 'Instagram URL',
			'name' => 'instagram_url',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'url',
			'value' => NULL,
			'menu_order' => 0,
			'instructions' => '',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_64c1b21c4c024',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://www.instagram.com/ericbuschphotography/',
			'_name' => 'instagram_url',
			'_valid' => 1,
		),
		1 => array(
			'ID' => 0,
			'key' => 'field_64c1b40511097',
			'label' => 'Contact Email',
			'name' => 'contact_email',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'email',
			'value' => NULL,
			'menu_order' => 1,
			'instructions' => 'This email address will be publicly exposed.',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_64c1b21c4c024',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'hello@ericbusch.ca',
			'prepend' => '',
			'append' => '',
			'_name' => 'contact_email',
			'_valid' => 1,
		),
		2 => array(
			'ID' => 0,
			'key' => 'field_64c3cf26c6612',
			'label' => 'Image New in Days',
			'name' => 'image_new_in_days',
			'aria-label' => '',
			'prefix' => 'acf',
			'type' => 'number',
			'value' => NULL,
			'menu_order' => 2,
			'instructions' => 'The number of days to consider an image in a collection to be new. Example: If you set this to 14, all images posted in the past 14 days will be considered "new".',
			'required' => 0,
			'id' => '',
			'class' => '',
			'conditional_logic' => 0,
			'parent' => 'group_64c1b21c4c024',
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 30,
			'min' => 1,
			'max' => 365,
			'placeholder' => '',
			'step' => 1,
			'prepend' => '',
			'append' => 'days',
			'_name' => 'image_new_in_days',
			'_valid' => 1,
		),
	),
	'location' => array(
		0 => array(
			0 => array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
	'_valid' => true,
	'local_file' => '/Users/eric/Sites/ericbusch-ca/wp-content/themes/ebca-theme/acf-json/group_64c1b21c4c024.json',
) );

